server:
  port: 8080


eureka: 
 instance:
  hostname: localhost
    
spring:
  application:
    name: api-gateway
  cloud: 
   gateway:
   
    globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST 
    routes: 
     - id: QUIZPRACTICES-QUESTION
       uri: lb://QUIZPRACTICES-QUESTION
       predicates: 
        - Path=/api/questions/**
        
     - id: QUIZPRACTICES-USER
       uri: lb://QUIZPRACTICES-USER 
       predicates: 
        - Path=/api/users/**
        
        
     - id: QUIZPRACTICES-TEST
       uri: lb://QUIZPRACTICES-TEST 
       predicates: 
        - Path=/api/tests/**      